### ISSUE TITLE
Figure out why github actions not triggered in some situations

### ISSUE THREAD

**Issue by scottyhq** [ICESAT-2HackWeek/website2022#78]
For example: 

https://github.com/ICESAT-2HackWeek/website2022/pull/70#issuecomment-1069381540 

https://github.com/ICESAT-2HackWeek/website2022/pull/77#issuecomment-1069548839

**Comment by weiji14** [comment]
Might just be an intermittent issue, some GitHub services were down on 16 and 17 March, see https://www.githubstatus.com/incidents/fpk08rxnqjz2, https://www.githubstatus.com/incidents/sksd097hm0y5

**Comment by scottyhq** [comment]
I'm pretty sure this was in fact due to intermittent issues, going to close
