### ISSUE TITLE
Improve GitHub Actions to expose execution errors and result in failed status

### ISSUE THREAD

**Issue by scottyhq** [ICESAT-2HackWeek/website2022#88]
Following up on https://github.com/ICESAT-2HackWeek/website2022/pull/87#issuecomment-1073350952 

It seems that our current build script does not raise an error recognized by github actions to raise a 'failed' status if notebooks fail to execute.
 https://github.com/ICESAT-2HackWeek/website2022/blob/3c59a0c8461b681b0fac7f3a275d6835d7ab9ceb/.github/actions/buildresources/action.yaml#L35

Also the specific build error doesn't show up in the [build log]( https://github.com/ICESAT-2HackWeek/website2022/runs/5619525525?check_suite_focus=true#step:4:1963), just a line like (`Last execution failed with traceback saved in /home/runner/work/website2022/website2022/book/_build/html/reports/data_access_3_icepyx.log`. So we have to download the build artifact folder and look at the specific Traceback:

```pytb
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#view a short list of order IDs
region_a.granules.orderIDs

AttributeError: 'Granules' object has no attribute 'orderIDs'
```

**Comment by scottyhq** [comment]
> @scottyhq I'm not sure why this is showing up as an error, since it ultimately executes and renders the output in the book... 

It was a temporary issue b/c the preceding cell had a `skip-execution` metadata tag. Just used it as an example to do a better job of exposing those errors directly in the CI logs.

**Comment by scottyhq** [comment]
Partially addressed with https://github.com/ICESAT-2HackWeek/website2022/blob/c2e5e3f57f2ca96d9ac815fac0649f6c4e084db9/.github/actions/buildresources/action.yaml#L37-L40

The build_resources.sh exit codes can still mean the action will 'succeed' even if building a notebook fails...

**Comment by scottyhq** [comment]
@jomey any thoughts on making `build_resources.sh` return a fail code that causes CI check to not pass if there is a build execution error? https://github.com/ICESAT-2HackWeek/website2022/runs/5683833811?check_suite_focus=true

**Comment by jomey** [comment]
Hm .. interesting

This method checks for the exit code of the last command and would exit the script if there was a failure.
https://github.com/ICESAT-2HackWeek/website2022/blob/76702cbbfa7e674b0d40e58547821fdc2cf10683/scripts/build_resources.sh#L23

Maybe the `jupyter-book` command does return 0 even if there was an error?
Could try using the `-W` flag

https://jupyterbook.org/basics/build.html#debug-your-books-build-process

**Comment by scottyhq** [comment]
This seems relevant https://github.com/executablebooks/jupyter-book/issues/1320. I will try adding `--warningiserror --keep-going` The green check is quite misleading currently and notebooks that fail to execute are rendered without any of their outputs (https://github.com/ICESAT-2HackWeek/website2022/pull/111)
